### ISSUE TITLE
Too many redirect error on new installation

### ISSUE THREAD

**Issue by Necc86** [Misterbabou/gptwol#20]
On a brand new docker deployment i get ERR_TOO_MANY_REDIRECTS while trying to load the webpage.

/app/db/computers.txt -> 0 byte
/etc/cron.d/gptwol -> 0 byte

docker compose:

```
services:
  gptwol:
    image: misterbabou/gptwol:latest
    container_name: wake_on_lan_gui
    network_mode: host
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /share/Docker/wake_on_lan/db:/app/db
      - /share/Docker/wake_on_lan/cron:/etc/cron.d
```

stack.env:

```
PORT=3060 #Free Port on Your host; default is 5000
TZ=Europe/Budapest #Set your timezone for Cron; default is UTC
ENABLE_LOGIN=false # Enable or disable login; You would be able to access with USERNAME and PASSWORD; default is false
USERNAME=[redacted] # Set a username; default is admin
PASSWORD=[redacted] # Set a password; default is admin
SCRIPT_NAME=/ # Uncomment this line to run the app under a prefix; default is /
ENABLE_ADD_DEL=true # Enable or disable ADD computer and Delete computer buttons; default is true
ENABLE_REFRESH=true # Enable or disable automatic status refresh; default is true
REFRESH_INTERVAL=30 # Uncomment to change status check for icmp, arp or tcp, can be 15, 30 or 60 (seconds); default value is 30 seconds
PING_TIMEOUT=300 #Uncomment to change the time to wait for a ping answer in (in ms); default value is 300 milliseconds
ARP_TIMEOUT=300 #Uncomment to change the time to wait for a arp answer in (in ms); default value is 300 milliseconds
TCP_TIMEOUT=1 #Uncomment to change the time to wait for a tcp check (in s);  default value 1 second
```

Container log (didn't paid attention and got cut off at 100 lines, app listens on 0.0.0.0:3060)
[_wake_on_lan_gui_logs.txt](https://github.com/user-attachments/files/20292486/_wake_on_lan_gui_logs.txt)
